FROM nginx
COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY updateStats.js /usr/share/nginx/html/updateStats.js
COPY logo.png /usr/share/nginx/html/logo.png
