services:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: password
      MYSQL_USER: acit3855
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: events
    ports:
      - 3306:3306
