datastore:
  filename: /data/data.json

scheduler:
  interval: 5

eventstores:
  match_history:
    url: http://storage:8090/league/match_history
  champion_winrate:
    url: http://storage:8090/league/champion_winrate
